name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -e .
      - run: python - << 'PY'
        import json
        from unification.persona_loader import load_imprint
        info, imprint = load_imprint(None)
        print(json.dumps({"selected": info["id"], "keys": list(imprint.keys())}))
        PY
